import type { DriftConfig } from '../types.js';

export const DEFAULT_CONFIG: DriftConfig = {
  general: {
    default_window: '12h',
    theme: 'dark',
  },
  repos: [],
  agents: {
    authors: [
      'dependabot[bot]',
      'renovate[bot]',
      'github-actions[bot]',
    ],
    message_patterns: [
      '\\[AGENT\\]',
      'forge:',
      'auto:',
      'Co-Authored-By:.*claude',
      'Co-Authored-By:.*copilot',
      'Co-Authored-By:.*cursor',
      'Generated by',
    ],
  },
};

export const CONFIG_DIR = '~/.drift';
export const CONFIG_FILE = '~/.drift/config.toml';
export const DB_FILE = '~/.drift/sessions.db';

export const SESSION_GAP_MINUTES = 10;
